# Generated by Django 5.1.4 on 2024-12-30 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estadio', models.CharField(max_length=120)),
                ('data', models.DateTimeField()),
                ('gols_casa', models.IntegerField()),
                ('gols_fora', models.IntegerField()),
                ('status', models.CharField(choices=[('Realizado', 'Realizado'), ('Não Realizado', 'Não Realizado'), ('Adiado', 'Adiado'), ('Cancelado', 'Cancelado')], max_length=20)),
                ('clube_casa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogos_casa', to='clubes.clube')),
                ('clube_fora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogos_fora', to='clubes.clube')),
                ('guarda_rede_casa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partida_casa_guarda_redes', to='clubes.jogador')),
                ('guarda_rede_fora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partida_fora_guarda_redes', to='clubes.jogador')),
                ('jogadores_em_campo', models.ManyToManyField(related_name='partidas', to='clubes.jogador')),
            ],
            options={
                'verbose_name': 'Jogo',
                'verbose_name_plural': 'Jogos',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='Golo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempo', models.TimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('Cabeça', 'Cabeça'), ('Remate', 'Remate'), ('Livre', 'Livre'), ('Pênalti', 'Pênalti'), ('Acrobático', 'Acrobático')], max_length=20)),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubes.jogador')),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jogos.jogo')),
            ],
            options={
                'verbose_name': 'Golo',
                'verbose_name_plural': 'Golos',
                'ordering': ['-tempo'],
            },
        ),
    ]
