# Generated by Django 5.1.4 on 2024-12-30 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubes', '0001_initial'),
        ('jogos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campeonato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('temporada', models.CharField(max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name='jogo',
            name='campeonato',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='jogos', to='jogos.campeonato'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='jogo',
            constraint=models.UniqueConstraint(fields=('campeonato', 'clube_casa', 'clube_fora'), name='unique_jogo_mesmo_campeonato_1'),
        ),
        migrations.AddConstraint(
            model_name='jogo',
            constraint=models.UniqueConstraint(fields=('campeonato', 'clube_fora', 'clube_casa'), name='unique_jogo_mesmo_campeonato_2'),
        ),
    ]
