# Generated by Django 5.1.4 on 2024-12-30 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubes', '0002_rename_capitao_jogador_is_capitao_and_more'),
        ('jogos', '0002_campeonato_jogo_campeonato_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='jogo',
            name='unique_jogo_mesmo_campeonato_1',
        ),
        migrations.RemoveConstraint(
            model_name='jogo',
            name='unique_jogo_mesmo_campeonato_2',
        ),
        migrations.RemoveField(
            model_name='jogo',
            name='jogadores_em_campo',
        ),
        migrations.AddField(
            model_name='jogo',
            name='jogadores_casa',
            field=models.ManyToManyField(limit_choices_to={'clube__isnull': False}, related_name='partidas_casa', to='clubes.jogador'),
        ),
        migrations.AddField(
            model_name='jogo',
            name='jogadores_fora',
            field=models.ManyToManyField(limit_choices_to={'clube__isnull': False}, related_name='partidas_fora', to='clubes.jogador'),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='guarda_rede_casa',
            field=models.ForeignKey(blank=True, limit_choices_to={'posicao': 'guarda_rede'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partida_casa_guarda_redes', to='clubes.jogador'),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='guarda_rede_fora',
            field=models.ForeignKey(blank=True, limit_choices_to={'posicao': 'guarda_rede'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partida_fora_guarda_redes', to='clubes.jogador'),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='status',
            field=models.CharField(choices=[('Realizado', 'Realizado'), ('Não Realizado', 'Não Realizado'), ('Adiado', 'Adiado'), ('Cancelado', 'Cancelado')], default='Não Realizado', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='jogo',
            constraint=models.UniqueConstraint(fields=('campeonato', 'clube_casa', 'clube_fora'), name='unique_jogo_mesmo_campeonato'),
        ),
    ]
