# Generated by Django 5.1.4 on 2024-12-30 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jogador',
            old_name='capitao',
            new_name='is_capitao',
        ),
        migrations.AlterField(
            model_name='jogador',
            name='posicao',
            field=models.CharField(choices=[('Guarda-Redes', 'Guarda-Redes'), ('Defesa Central', 'Defesa Central'), ('Lateral Esquerda', 'Lateral Esquerda'), ('Lateral Direita', 'Lateral Direita'), ('Meio Central', 'Meio Central'), ('Meia Defensivo', 'Meia Defensivo'), ('Meia Ofensiva', 'Meia Ofensiva'), ('Ponta Direita', 'Ponta Direita'), ('Ponta Esquerda', 'Ponta Esquerda')], max_length=20),
        ),
    ]
