# Generated by Django 5.1.4 on 2024-12-30 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubes', '0002_rename_capitao_jogador_is_capitao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clube',
            name='avatar',
            field=models.ImageField(default=0, upload_to='media'),
            preserve_default=False,
        ),
    ]
