# Generated by Django 5.1.4 on 2025-01-02 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubes', '0003_clube_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='clube',
            name='treinador',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
