# Generated by Django 5.1.4 on 2025-01-02 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubes', '0004_clube_treinador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogador',
            name='posicao',
            field=models.CharField(choices=[('Guarda-Redes', 'GD'), ('Defesa', 'DF'), ('Meio-campo', 'MD'), ('Avançado', 'AV')], max_length=20),
        ),
    ]
